/**
 * Triage Emergency Modal Component
 * Displays when backend deterministic triage detects red-flags or urgent clinical criteria.
 * Strictly uses non-diagnostic, safety-first clinical guidance.
 */
import React from 'react';
import {
  View,
  Text,
  Modal,
  StyleSheet,
  TouchableOpacity,
  Linking,
  ScrollView,
} from 'react-native';
import { colors, typography, spacing, borderRadius } from '../../constants/theme';
import { TriageResult } from '../../types';

interface EmergencyModalProps {
  visible: boolean;
  triage: TriageResult | null;
  onDismiss: () => void;
  hospitalHotline?: string;
}

export const EmergencyModal: React.FC<EmergencyModalProps> = ({
  visible,
  triage,
  onDismiss,
  hospitalHotline = '+91 22 2845 9999',
}) => {
  const callEmergency = () => {
    Linking.openURL(`tel:${hospitalHotline.replace(/\s+/g, '')}`).catch(() => {});
  };

  const callNationalHelpline = () => {
    Linking.openURL('tel:112').catch(() => {});
  };

  const redFlags = triage?.red_flags_detected || triage?.trigger_symptoms || [];

  return (
    <Modal visible={visible} transparent animationType="slide" onRequestClose={onDismiss}>
      <View style={styles.overlay}>
        <View style={styles.container}>
          {/* Urgent Warning Header */}
          <View style={styles.header}>
            <View style={styles.badgeRow}>
              <View style={styles.alertIconBadge}>
                <Text style={styles.alertEmoji}>🚨</Text>
              </View>
              <View>
                <Text style={styles.alertTitle}>Clinical Alert Detected</Text>
                <Text style={styles.alertSubtitle}>Immediate Medical Attention Advised</Text>
              </View>
            </View>
          </View>

          <ScrollView style={styles.content} showsVerticalScrollIndicator={false}>
            {/* Clear, Calm Safety Guidance */}
            <View style={styles.advisoryBox}>
              <Text style={styles.advisoryTitle}>Important Health Notice</Text>
              <Text style={styles.advisoryBody}>
                The symptoms you reported may require urgent medical evaluation. Please do not wait
                for a standard outpatient appointment.
              </Text>
            </View>

            {/* Red Flags List from Backend */}
            {redFlags.length > 0 && (
              <View style={styles.symptomsBox}>
                <Text style={styles.symptomsLabel}>Reported Symptoms of Concern:</Text>
                {redFlags.map((item, index) => (
                  <View key={index} style={styles.symptomItem}>
                    <Text style={styles.bullet}>•</Text>
                    <Text style={styles.symptomText}>{item}</Text>
                  </View>
                ))}
              </View>
            )}

            {/* Backend Emergency Instructions */}
            {triage?.emergency_instructions && (
              <View style={styles.instructionsBox}>
                <Text style={styles.instructionsTitle}>Instructions:</Text>
                <Text style={styles.instructionsBody}>{triage.emergency_instructions}</Text>
              </View>
            )}

            {/* Non-Diagnostic Disclaimer */}
            <Text style={styles.disclaimerText}>
              This advisory is an automated safety alert generated by hospital triage rules. It is not
              a definitive medical diagnosis.
            </Text>
          </ScrollView>

          {/* Action Buttons */}
          <View style={styles.actions}>
            <TouchableOpacity onPress={callEmergency} style={styles.primaryButton}>
              <Text style={styles.phoneIcon}>📞</Text>
              <Text style={styles.primaryButtonText}>
                Call Hospital Emergency ({hospitalHotline})
              </Text>
            </TouchableOpacity>

            <TouchableOpacity onPress={callNationalHelpline} style={styles.helplineButton}>
              <Text style={styles.helplineText}>Call National Emergency (112)</Text>
            </TouchableOpacity>

            <TouchableOpacity onPress={onDismiss} style={styles.dismissButton}>
              <Text style={styles.dismissText}>I Understand & Will Seek Help</Text>
            </TouchableOpacity>
          </View>
        </View>
      </View>
    </Modal>
  );
};

const styles = StyleSheet.create({
  overlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.8)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: spacing.md,
  },
  container: {
    width: '100%',
    maxWidth: 420,
    backgroundColor: colors.surface,
    borderRadius: borderRadius.xxl,
    overflow: 'hidden',
    borderWidth: 2,
    borderColor: colors.error,
    maxHeight: '90%',
  },
  header: {
    backgroundColor: colors.errorContainer,
    padding: spacing.lg,
    borderBottomWidth: 1,
    borderBottomColor: '#FECDD3',
  },
  badgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.md,
  },
  alertIconBadge: {
    width: 44,
    height: 44,
    borderRadius: 22,
    backgroundColor: colors.error,
    alignItems: 'center',
    justifyContent: 'center',
  },
  alertEmoji: {
    fontSize: 22,
  },
  alertTitle: {
    fontSize: 17,
    fontWeight: '800',
    color: colors.onErrorContainer,
  },
  alertSubtitle: {
    fontSize: 12,
    fontWeight: '600',
    color: colors.error,
    marginTop: 2,
  },
  content: {
    padding: spacing.lg,
  },
  advisoryBox: {
    backgroundColor: '#FFF1F2',
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    borderLeftWidth: 4,
    borderLeftColor: colors.error,
    marginBottom: spacing.md,
  },
  advisoryTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: colors.onErrorContainer,
    marginBottom: 4,
  },
  advisoryBody: {
    fontSize: 13,
    color: colors.textPrimary,
    lineHeight: 18,
  },
  symptomsBox: {
    backgroundColor: colors.surfaceContainerLow,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.md,
  },
  symptomsLabel: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.textSecondary,
    marginBottom: 6,
  },
  symptomItem: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    marginBottom: 4,
  },
  bullet: {
    fontSize: 14,
    color: colors.error,
    marginRight: 6,
    lineHeight: 18,
  },
  symptomText: {
    fontSize: 13,
    fontWeight: '600',
    color: colors.textPrimary,
    flex: 1,
  },
  instructionsBox: {
    backgroundColor: colors.infoContainer,
    padding: spacing.md,
    borderRadius: borderRadius.lg,
    marginBottom: spacing.md,
  },
  instructionsTitle: {
    fontSize: 12,
    fontWeight: '700',
    color: colors.onInfoContainer,
    marginBottom: 2,
  },
  instructionsBody: {
    fontSize: 13,
    color: colors.onInfoContainer,
    lineHeight: 18,
  },
  disclaimerText: {
    fontSize: 11,
    color: colors.textMuted,
    fontStyle: 'italic',
    textAlign: 'center',
    marginBottom: spacing.sm,
  },
  actions: {
    padding: spacing.lg,
    backgroundColor: colors.surfaceContainerLow,
    borderTopWidth: 1,
    borderTopColor: colors.border,
    gap: spacing.sm,
  },
  primaryButton: {
    minHeight: 48,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.error,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    paddingHorizontal: spacing.md,
  },
  phoneIcon: {
    fontSize: 16,
    marginRight: 6,
  },
  primaryButtonText: {
    color: colors.textLight,
    fontSize: 14,
    fontWeight: '800',
  },
  helplineButton: {
    minHeight: 44,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.surface,
    borderWidth: 1.5,
    borderColor: colors.error,
    alignItems: 'center',
    justifyContent: 'center',
  },
  helplineText: {
    color: colors.error,
    fontSize: 13,
    fontWeight: '700',
  },
  dismissButton: {
    minHeight: 40,
    alignItems: 'center',
    justifyContent: 'center',
  },
  dismissText: {
    fontSize: 12,
    color: colors.textMuted,
    fontWeight: '600',
    textDecorationLine: 'underline',
  },
});
