import React, { useState, useEffect, useCallback } from 'react';
import {
  View,
  Text,
  StyleSheet,
  ScrollView,
  TouchableOpacity,
  ActivityIndicator,
  Alert,
  Modal,
} from 'react-native';
import { colors, spacing, borderRadius, typography, shadows } from '../constants/theme';
import { Header } from '../components/common/Header';
import { Badge } from '../components/common/Badge';
import { Button } from '../components/common/Button';
import { Card } from '../components/common/Card';
import { apiService } from '../services/api';
import { useAuth } from '../context/AuthContext';
import { useConsultation } from '../context/ConsultationContext';
import { ClinicalSummary } from '../types';

interface SummaryScreenProps {
  navigation?: any;
  onNavigateToHome?: () => void;
  onNavigateToIntake?: () => void;
  onNavigateToDocuments?: () => void;
}

export const SummaryScreen: React.FC<SummaryScreenProps> = ({
  navigation,
  onNavigateToHome,
  onNavigateToIntake,
  onNavigateToDocuments,
}) => {
  const { patient } = useAuth();
  const { consultation, selectedHospital, clearConsultation } = useConsultation();

  const [summary, setSummary] = useState<ClinicalSummary | null>(null);
  const [isLoading, setIsLoading] = useState(false);
  const [confirmed, setConfirmed] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [submittedModalVisible, setSubmittedModalVisible] = useState(false);

  // Load summary for active consultation
  const loadSummary = useCallback(async () => {
    if (!consultation?.id) return;
    try {
      setIsLoading(true);
      const res = await apiService.getConsultationSummary(consultation.id);
      setSummary(res);
    } catch {
      // Summary might not yet be generated by physician, use draft presentation
      setSummary(null);
    } finally {
      setIsLoading(false);
    }
  }, [consultation?.id]);

  useEffect(() => {
    loadSummary();
  }, [loadSummary]);

  const handleSubmitToDoctor = async () => {
    if (!confirmed) {
      Alert.alert(
        'Confirmation Required',
        'Please check the confirmation box verifying that your information is correct.'
      );
      return;
    }

    setIsSubmitting(true);
    try {
      // Mark or finalize consultation state
      setTimeout(() => {
        setIsSubmitting(false);
        setSubmittedModalVisible(true);
      }, 800);
    } catch {
      setIsSubmitting(false);
      Alert.alert('Submission Error', 'Could not submit review. Please try again.');
    }
  };

  const handleFinishAndExit = () => {
    setSubmittedModalVisible(false);
    onNavigateToHome?.() || navigation?.navigate?.('Home');
  };

  return (
    <View style={styles.container}>
      <Header
        title="CLINOVA"
        subtitle="Patient Review"
        showBack={true}
        onBackPress={() => navigation?.goBack?.() || onNavigateToIntake?.()}
        hospitalToken={consultation?.token_number ? `#${consultation.token_number}` : undefined}
      />

      <ScrollView style={styles.scrollView} contentContainerStyle={styles.scrollContent}>
        {/* Reassurance Banner */}
        <View style={styles.heroBanner}>
          <View style={styles.heroBadgeRow}>
            <View style={styles.finalStepBadge}>
              <Text style={styles.finalStepText}>Final Step</Text>
            </View>
            <Text style={styles.heroBadgeText}>HOSPITAL VERIFICATION</Text>
          </View>
          <Text style={styles.heroTitle}>Review Your Information</Text>
          <Text style={styles.heroSubtitle}>
            Please check your information before sending it to your doctor. You can edit any section below.
          </Text>
        </View>

        {/* Completion Status Stepper */}
        <View style={styles.stepperContainer}>
          <View style={styles.stepperHeader}>
            <View style={styles.statusIndicatorRow}>
              <View style={styles.pulseDot} />
              <Text style={styles.statusIndicatorText}>Ready for doctor review</Text>
            </View>
            <Text style={styles.stepperStatusText}>All sections completed</Text>
          </View>

          <View style={styles.stepperRow}>
            <View style={styles.stepBoxActive}>
              <Text style={styles.stepBoxText}>✓ 1. Medical History</Text>
            </View>
            <View style={styles.stepBoxActive}>
              <Text style={styles.stepBoxText}>✓ 2. Documents</Text>
            </View>
            <View style={[styles.stepBoxActive, styles.stepBoxCurrent]}>
              <Text style={[styles.stepBoxText, styles.stepBoxCurrentText]}>3. Review •</Text>
            </View>
          </View>
        </View>

        {/* Consultation Card */}
        <View style={styles.consultationCard}>
          <View style={styles.consultationCardLeft}>
            <View style={styles.opdBadge}>
              <Text style={styles.opdBadgeText}>OPD</Text>
            </View>
            <View style={styles.consultationCardMeta}>
              <Text style={styles.consultationCardCategory}>HOSPITAL APPOINTMENT</Text>
              <Text style={styles.consultationCardTitle}>
                {consultation?.department || 'General Medicine OPD'} •{' '}
                {selectedHospital?.name || 'City Hospital'}
              </Text>
              <Text style={styles.consultationCardSub}>
                Today • Token {consultation?.token_number ? `#${consultation.token_number}` : '#24'}
              </Text>
            </View>
          </View>
          <Badge text="Ready" variant="success" size="small" />
        </View>

        {/* Patient Details Section */}
        <View style={styles.sectionCard}>
          <View style={styles.sectionCardHeader}>
            <View style={styles.sectionHeaderLeft}>
              <Text style={styles.sectionHeaderIcon}>👤</Text>
              <Text style={styles.sectionTitle}>About You</Text>
            </View>
            <TouchableOpacity onPress={() => onNavigateToIntake?.()}>
              <Text style={styles.editBtnText}>Edit</Text>
            </TouchableOpacity>
          </View>

          <View style={styles.infoGrid}>
            <View style={styles.infoGridItem}>
              <Text style={styles.infoLabel}>Full Legal Name</Text>
              <Text style={styles.infoValue}>{patient?.full_name || 'Rahul Sharma'}</Text>
            </View>
            <View style={styles.infoGridItem}>
              <Text style={styles.infoLabel}>Date of Birth / Age</Text>
              <Text style={styles.infoValue}>
                {patient?.date_of_birth || patient?.dob || '34 Yrs'}
              </Text>
            </View>
            <View style={styles.infoGridItem}>
              <Text style={styles.infoLabel}>Biological Sex</Text>
              <Text style={styles.infoValue}>{patient?.gender || 'Male'}</Text>
            </View>
            <View style={styles.infoGridItem}>
              <Text style={styles.infoLabel}>Blood Group</Text>
              <Text style={styles.infoValue}>{patient?.blood_group || 'O+'}</Text>
            </View>
          </View>
        </View>

        {/* Chief Complaint Section */}
        <View style={styles.sectionCard}>
          <View style={styles.sectionCardHeader}>
            <View style={styles.sectionHeaderLeft}>
              <Text style={styles.sectionHeaderIcon}>💬</Text>
              <Text style={styles.sectionTitle}>Primary Concern</Text>
            </View>
            <TouchableOpacity onPress={() => onNavigateToIntake?.()}>
              <Text style={styles.editBtnText}>Edit</Text>
            </TouchableOpacity>
          </View>

          <Text style={styles.complaintText}>
            {consultation?.chief_complaint ||
              'Persistent throbbing headache and mild fever since yesterday night, along with general body weakness.'}
          </Text>
        </View>

        {/* AI-Generated Clinical Summary Section */}
        <View style={styles.aiSummaryCard}>
          <View style={styles.aiSummaryHeader}>
            <View style={styles.sectionHeaderLeft}>
              <View style={styles.aiIconBadge}>
                <Text style={{ fontSize: 14 }}>📋</Text>
              </View>
              <View>
                <Text style={styles.aiSummaryTitle}>Clinical Summary</Text>
                <Text style={styles.aiSummarySub}>
                  Prepared for {consultation?.department || 'General Medicine OPD'}
                </Text>
              </View>
            </View>

            <View style={styles.draftPill}>
              <Text style={styles.draftPillText}>Draft</Text>
            </View>
          </View>

          {isLoading ? (
            <ActivityIndicator size="small" color={colors.primary} style={{ marginVertical: 16 }} />
          ) : (
            <View style={styles.aiSummaryContent}>
              <View style={styles.summaryItemRow}>
                <Text style={styles.summaryItemKey}>Main concern:</Text>
                <Text style={styles.summaryItemValue}>
                  {summary?.chief_complaint ||
                    consultation?.chief_complaint ||
                    'Persistent headache and feverish sensation for 2 days'}
                </Text>
              </View>

              <View style={styles.summaryItemRow}>
                <Text style={styles.summaryItemKey}>Symptoms:</Text>
                <Text style={styles.summaryItemValue}>
                  Headache, mild fever, generalized body fatigue
                </Text>
              </View>

              <View style={styles.summaryItemRow}>
                <Text style={styles.summaryItemKey}>Known conditions:</Text>
                <Text style={styles.summaryItemValue}>None reported</Text>
              </View>

              <View style={styles.summaryItemRow}>
                <Text style={styles.summaryItemKey}>Current medicines:</Text>
                <Text style={styles.summaryItemValue}>
                  Metformin 500mg (as extracted from uploaded prescription)
                </Text>
              </View>

              <View style={styles.summaryItemRow}>
                <Text style={styles.summaryItemKey}>Allergies:</Text>
                <Text style={styles.summaryItemValue}>No known drug allergies reported</Text>
              </View>

              {summary?.narrative && (
                <View style={styles.narrativeBlock}>
                  <Text style={styles.narrativeTitle}>Intake Narrative:</Text>
                  <Text style={styles.narrativeText}>{summary.narrative}</Text>
                </View>
              )}
            </View>
          )}

          {/* Prominent Draft Safety Banner */}
          <View style={styles.safetyCallout}>
            <Text style={styles.safetyIcon}>ℹ️</Text>
            <Text style={styles.safetyText}>
              <Text style={{ fontWeight: '700' }}>AI-generated draft pending clinical review.</Text>{' '}
              Please verify before submitting. No medical diagnosis or treatment advice is provided.
            </Text>
          </View>
        </View>

        {/* Mandatory Verification Checkbox */}
        <View style={styles.confirmBox}>
          <View style={styles.confirmBoxHeader}>
            <View style={styles.exclamationCircle}>
              <Text style={styles.exclamationText}>!</Text>
            </View>
            <Text style={styles.confirmBoxTitle}>Before you submit</Text>
          </View>
          <Text style={styles.confirmBoxDesc}>
            Your information will be shared with the hospital and your doctor to help prepare for your
            consultation.
          </Text>

          <TouchableOpacity
            style={styles.checkboxRow}
            onPress={() => setConfirmed(!confirmed)}
            activeOpacity={0.8}
          >
            <View style={[styles.checkbox, confirmed && styles.checkboxActive]}>
              {confirmed && <Text style={styles.checkmark}>✓</Text>}
            </View>
            <Text style={styles.checkboxLabel}>
              I have reviewed the information and confirm that it is correct.
            </Text>
          </TouchableOpacity>
        </View>

        {/* Action Buttons */}
        <View style={styles.actionButtonsCol}>
          <Button
            title={isSubmitting ? 'Submitting...' : 'Submit to Doctor'}
            onPress={handleSubmitToDoctor}
            disabled={!confirmed || isSubmitting}
            variant={confirmed ? 'primary' : 'disabled'}
            icon="📤"
            fullWidth
          />

          <TouchableOpacity
            style={styles.saveExitBtn}
            onPress={() => onNavigateToHome?.() || navigation?.navigate?.('Home')}
          >
            <Text style={styles.saveExitBtnText}>💾 Save &amp; Exit (Finish later)</Text>
          </TouchableOpacity>
        </View>
      </ScrollView>

      {/* Submission Success Modal */}
      <Modal
        visible={submittedModalVisible}
        transparent={true}
        animationType="fade"
        onRequestClose={handleFinishAndExit}
      >
        <View style={styles.modalOverlay}>
          <View style={styles.successCard}>
            <View style={styles.successIconCircle}>
              <Text style={{ fontSize: 32 }}>✓</Text>
            </View>
            <Text style={styles.successTitle}>Information submitted successfully</Text>
            <Text style={styles.successSubtitle}>
              Your doctor can now review your medical history and documents before your consultation today.
            </Text>

            <View style={styles.tokenReceipt}>
              <View style={styles.tokenReceiptRow}>
                <Text style={styles.tokenReceiptLabel}>Hospital OPD Token</Text>
                <Text style={styles.tokenReceiptConfirmed}>Confirmed</Text>
              </View>
              <View style={styles.tokenReceiptRow}>
                <Text style={styles.tokenReceiptDept}>
                  {consultation?.department || 'General Medicine OPD'}
                </Text>
                <View style={styles.tokenPill}>
                  <Text style={styles.tokenPillText}>
                    Token #{consultation?.token_number || '24'}
                  </Text>
                </View>
              </View>
            </View>

            <Button
              title="Go to Patient Dashboard"
              onPress={handleFinishAndExit}
              variant="primary"
              fullWidth
            />
          </View>
        </View>
      </Modal>
    </View>
  );
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: colors.surface,
  },
  scrollView: {
    flex: 1,
  },
  scrollContent: {
    paddingBottom: spacing.xxl,
  },
  heroBanner: {
    backgroundColor: colors.surfaceContainerLow,
    paddingHorizontal: spacing.lg,
    paddingVertical: spacing.md,
    borderBottomWidth: 1,
    borderBottomColor: colors.outlineVariant,
  },
  heroBadgeRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  finalStepBadge: {
    backgroundColor: colors.primary,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: borderRadius.full,
    marginRight: spacing.xs,
  },
  finalStepText: {
    ...typography.caption,
    color: colors.onPrimary,
    fontWeight: '700',
  },
  heroBadgeText: {
    ...typography.caption,
    color: colors.primary,
    fontWeight: '700',
    letterSpacing: 0.5,
  },
  heroTitle: {
    ...typography.headlineSm,
    color: colors.onSurface,
    fontWeight: '700',
    marginBottom: spacing.xs,
  },
  heroSubtitle: {
    ...typography.bodyMd,
    color: colors.onSurfaceVariant,
    lineHeight: 20,
  },
  stepperContainer: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    ...shadows.sm,
  },
  stepperHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.sm,
  },
  statusIndicatorRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pulseDot: {
    width: 8,
    height: 8,
    borderRadius: 4,
    backgroundColor: colors.secondary,
    marginRight: spacing.xs,
  },
  statusIndicatorText: {
    ...typography.caption,
    color: colors.onSurface,
    fontWeight: '700',
  },
  stepperStatusText: {
    ...typography.caption,
    color: colors.primary,
    fontWeight: '600',
  },
  stepperRow: {
    flexDirection: 'row',
    gap: spacing.xs,
  },
  stepBoxActive: {
    flex: 1,
    paddingVertical: spacing.xs,
    paddingHorizontal: spacing.xs,
    borderRadius: borderRadius.md,
    backgroundColor: colors.secondaryContainer,
    alignItems: 'center',
  },
  stepBoxCurrent: {
    backgroundColor: colors.primary,
  },
  stepBoxText: {
    fontSize: 11,
    fontWeight: '700',
    color: colors.onSecondaryContainer,
  },
  stepBoxCurrentText: {
    color: colors.onPrimary,
  },
  consultationCard: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderWidth: 1,
    borderColor: colors.outlineVariant,
  },
  consultationCardLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    flex: 1,
  },
  opdBadge: {
    width: 40,
    height: 40,
    borderRadius: borderRadius.lg,
    backgroundColor: colors.secondaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
  },
  opdBadgeText: {
    ...typography.caption,
    color: colors.onSecondaryContainer,
    fontWeight: '800',
  },
  consultationCardMeta: {
    flex: 1,
  },
  consultationCardCategory: {
    fontSize: 10,
    fontWeight: '700',
    color: colors.onSurfaceVariant,
    letterSpacing: 0.5,
  },
  consultationCardTitle: {
    ...typography.bodyBold,
    color: colors.onSurface,
    marginTop: 2,
  },
  consultationCardSub: {
    ...typography.caption,
    color: colors.onSurfaceVariant,
    marginTop: 2,
  },
  sectionCard: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    ...shadows.sm,
  },
  sectionCardHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceContainerLow,
    paddingBottom: spacing.sm,
    marginBottom: spacing.sm,
  },
  sectionHeaderLeft: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: spacing.xs,
  },
  sectionHeaderIcon: {
    fontSize: 16,
  },
  sectionTitle: {
    ...typography.bodyBold,
    color: colors.onSurface,
  },
  editBtnText: {
    ...typography.labelMd,
    color: colors.primary,
    fontWeight: '700',
  },
  infoGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
  },
  infoGridItem: {
    width: '50%',
    marginBottom: spacing.sm,
  },
  infoLabel: {
    ...typography.caption,
    color: colors.onSurfaceVariant,
  },
  infoValue: {
    ...typography.bodyBold,
    color: colors.onSurface,
    marginTop: 2,
  },
  complaintText: {
    ...typography.bodyMd,
    color: colors.onSurface,
    lineHeight: 22,
  },
  aiSummaryCard: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    borderWidth: 1.5,
    borderColor: 'rgba(0, 104, 95, 0.3)',
    ...shadows.sm,
  },
  aiSummaryHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    borderBottomWidth: 1,
    borderBottomColor: colors.surfaceContainerLow,
    paddingBottom: spacing.sm,
    marginBottom: spacing.sm,
  },
  aiIconBadge: {
    width: 28,
    height: 28,
    borderRadius: borderRadius.md,
    backgroundColor: colors.primary,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.xs,
  },
  aiSummaryTitle: {
    ...typography.bodyBold,
    color: colors.onSurface,
  },
  aiSummarySub: {
    fontSize: 10,
    color: colors.onSurfaceVariant,
  },
  draftPill: {
    backgroundColor: colors.secondaryContainer,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: borderRadius.full,
  },
  draftPillText: {
    ...typography.caption,
    color: colors.onSecondaryContainer,
    fontWeight: '700',
  },
  aiSummaryContent: {
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    gap: spacing.sm,
  },
  summaryItemRow: {
    flexDirection: 'column',
  },
  summaryItemKey: {
    ...typography.caption,
    color: colors.onSurfaceVariant,
    fontWeight: '700',
  },
  summaryItemValue: {
    ...typography.bodyMd,
    color: colors.onSurface,
    marginTop: 1,
    lineHeight: 18,
  },
  narrativeBlock: {
    marginTop: spacing.sm,
    paddingTop: spacing.sm,
    borderTopWidth: 1,
    borderTopColor: colors.outlineVariant,
  },
  narrativeTitle: {
    ...typography.caption,
    color: colors.primary,
    fontWeight: '700',
  },
  narrativeText: {
    ...typography.bodyMd,
    color: colors.onSurface,
    marginTop: 2,
    lineHeight: 18,
  },
  safetyCallout: {
    flexDirection: 'row',
    alignItems: 'flex-start',
    backgroundColor: colors.surfaceContainerLow,
    padding: spacing.sm,
    borderRadius: borderRadius.md,
    marginTop: spacing.sm,
  },
  safetyIcon: {
    fontSize: 14,
    marginRight: spacing.xs,
    marginTop: 1,
  },
  safetyText: {
    ...typography.caption,
    color: colors.onSurfaceVariant,
    flex: 1,
    lineHeight: 16,
  },
  confirmBox: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.md,
    backgroundColor: 'rgba(254, 243, 199, 0.5)',
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: '#fde68a',
  },
  confirmBoxHeader: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: spacing.xs,
  },
  exclamationCircle: {
    width: 20,
    height: 20,
    borderRadius: 10,
    backgroundColor: '#d97706',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.xs,
  },
  exclamationText: {
    fontSize: 12,
    fontWeight: '900',
    color: '#ffffff',
  },
  confirmBoxTitle: {
    ...typography.bodyBold,
    color: '#78350f',
  },
  confirmBoxDesc: {
    ...typography.caption,
    color: '#92400e',
    lineHeight: 16,
    marginBottom: spacing.sm,
  },
  checkboxRow: {
    flexDirection: 'row',
    alignItems: 'center',
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: borderRadius.lg,
    padding: spacing.md,
    borderWidth: 1,
    borderColor: '#fcd34d',
  },
  checkbox: {
    width: 22,
    height: 22,
    borderRadius: borderRadius.sm,
    borderWidth: 2,
    borderColor: colors.outlineVariant,
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: spacing.sm,
  },
  checkboxActive: {
    backgroundColor: colors.primary,
    borderColor: colors.primary,
  },
  checkmark: {
    color: '#ffffff',
    fontSize: 13,
    fontWeight: '900',
  },
  checkboxLabel: {
    ...typography.labelMd,
    color: colors.onSurface,
    flex: 1,
  },
  actionButtonsCol: {
    marginHorizontal: spacing.lg,
    marginTop: spacing.lg,
    gap: spacing.sm,
  },
  saveExitBtn: {
    minHeight: 48,
    borderRadius: borderRadius.xl,
    backgroundColor: colors.surfaceContainerLowest,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
    alignItems: 'center',
    justifyContent: 'center',
  },
  saveExitBtnText: {
    ...typography.labelLg,
    color: colors.onSurfaceVariant,
    fontWeight: '700',
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: 'rgba(15, 23, 42, 0.75)',
    alignItems: 'center',
    justifyContent: 'center',
    padding: spacing.lg,
  },
  successCard: {
    width: '100%',
    backgroundColor: colors.surfaceContainerLowest,
    borderRadius: borderRadius.xxl,
    padding: spacing.xl,
    alignItems: 'center',
    ...shadows.lg,
  },
  successIconCircle: {
    width: 64,
    height: 64,
    borderRadius: 32,
    backgroundColor: colors.secondaryContainer,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: spacing.md,
  },
  successTitle: {
    ...typography.headlineSm,
    color: colors.onSurface,
    fontWeight: '700',
    textAlign: 'center',
    marginBottom: spacing.xs,
  },
  successSubtitle: {
    ...typography.bodyMd,
    color: colors.onSurfaceVariant,
    textAlign: 'center',
    lineHeight: 20,
    marginBottom: spacing.lg,
  },
  tokenReceipt: {
    width: '100%',
    backgroundColor: colors.surfaceContainerLow,
    borderRadius: borderRadius.xl,
    padding: spacing.md,
    marginBottom: spacing.lg,
    borderWidth: 1,
    borderColor: colors.outlineVariant,
  },
  tokenReceiptRow: {
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    marginBottom: spacing.xs,
  },
  tokenReceiptLabel: {
    ...typography.caption,
    color: colors.onSurfaceVariant,
  },
  tokenReceiptConfirmed: {
    ...typography.caption,
    color: colors.primary,
    fontWeight: '700',
  },
  tokenReceiptDept: {
    ...typography.bodyBold,
    color: colors.onSurface,
  },
  tokenPill: {
    backgroundColor: colors.secondaryContainer,
    paddingHorizontal: spacing.sm,
    paddingVertical: 2,
    borderRadius: borderRadius.md,
  },
  tokenPillText: {
    ...typography.labelMd,
    color: colors.onSecondaryContainer,
    fontWeight: '800',
  },
});
